development:
  adapter: postgresql
  encoding: unicode
  database: fables
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: fables_test
  pool: 5
  username: postgres
  password: postgres
